### ISSUE TITLE
Case modification

### ISSUE THREAD

**Issue by nateo729** [HigherOrderThinkers/Product#1]
plastic case cad needs to be updated so that motors fit properly.

**Comment by nateo729** [comment]
Might need to increase size of motor tray to allow for some neoprene. This will make unit near silent.

**Comment by nateo729** [comment]
Discovered that motors need to sit in there sideways.

**Comment by RobertPDuncan** [comment]
Slop glue on bolts. Excess wires need to be rubber glued down. Separate of motor wiring from boards to no cross connections.

**Comment by RobertPDuncan** [comment]
Possible sound dampening solution. Either epoxy glue in a flat mold for one side of the bolt. Or use thin layer of material in between bolt and magnet groups.

**Comment by RobertPDuncan** [comment]
Case does not easily slide down as designed. Possible fix is increase the height of the middle divider.

**Comment by RobertPDuncan** [comment]
Longevity of epoxy glue for power connector is uncertain. Possible solutions. Use a soldering iron to melt the two types of plastics on this inside together.

**Comment by RobertPDuncan** [comment]
Deposit new versions of code in this repository and variations of jamming algs.
